FROM python:3.11-slim as wherobots-harlequin

RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/*
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN pip install harlequin harlequin-wherobots

COPY ./gdea-cert.api ./gdea-cert.api
